### ISSUE TITLE
Is this available in the App Store?

### ISSUE THREAD

**Issue by ryanfortner** [fahimrahmanbooom/Duino-Coin_iOS_App#1]
Hi there, this is a great project! However I am unable to find it in the App Store.

Has it been removed, or restricted to certain countries>

**Comment by ra1n08** [comment]
idk
:>>

**Comment by ryanfortner** [comment]
@fahimrahmanbooom ?

**Comment by fahimrahmanbooom** [comment]
I’m sorry @ryanfortner . It’s still not on the AppStore because this cryptocurrency is currently not on the apple’s list and apple rejected the app. However if you have a mac you can install the app from the source code.

**Comment by ryanfortner** [comment]
> I’m sorry @ryanfortner . It’s still not on the AppStore because this cryptocurrency is currently not on the apple’s list and apple rejected the app. However if you have a mac you can install the app.

Do you mean that you can use a Mac to install it on an iOS device, or you can only install it on macOS?

**Comment by fahimrahmanbooom** [comment]
> > I’m sorry @ryanfortner . It’s still not on the AppStore because this cryptocurrency is currently not on the apple’s list and apple rejected the app. However if you have a mac you can install the app.
> 
> Do you mean that you can use a Mac to install it on an iOS device, or you can only install it on macOS?

Using a macOS you can install the app on your iPhone through Xcode.
